apiVersion: apps/v1
kind: Deployment 
metadata:
  name: myapp2-deployment
  labels:
    tier: front-end
spec:
  replicas: 2
  selector:
   matchLabels:
    tier: front-end
  template:
   metadata: 
    name: myapp2-pod
    labels:
      tier: front-end
   spec:
    containers:
    - name: myapp2-container
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80
  