apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mydeploy1
  labels:
    tier: front-end
spec:
 replicas: 3
 selector:
   matchLabels:
    tier: front-end
 template:
   metadata:
    name: mypod1
    labels:
      tier: front-end
   spec:
    containers:
     - name: myappcon1
       image: stacksimplify/kubenginx:3.0.0
